import json
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session
from ..database import get_db
from ..models import Package, Project, InstallSource
from .._time import utcnow

router = APIRouter()


@router.get("/{proj_id}/requirements.txt", response_class=PlainTextResponse)
def export_requirements(proj_id: int, db: Session = Depends(get_db)):
    proj = db.query(Project).get(proj_id)
    if not proj:
        raise HTTPException(404)
    lines = [
        f"{p.name}=={p.version}"
        for p in proj.packages
        if p.source == InstallSource.pip
    ]
    return "\n".join(lines) or "# No pip packages in this project\n"


@router.get("/{proj_id}/pacman-list", response_class=PlainTextResponse)
def export_pacman_list(proj_id: int, db: Session = Depends(get_db)):
    proj = db.query(Project).get(proj_id)
    if not proj:
        raise HTTPException(404)
    lines = [
        p.name
        for p in proj.packages
        if p.source in (InstallSource.pacman, InstallSource.aur)
    ]
    return "\n".join(lines) or "# No pacman/AUR packages in this project\n"


@router.get("/{proj_id}/reinstall.sh", response_class=PlainTextResponse)
def export_reinstall_script(proj_id: int, db: Session = Depends(get_db)):
    proj = db.query(Project).get(proj_id)
    if not proj:
        raise HTTPException(404)

    pacman_pkgs = [p.name for p in proj.packages if p.source == InstallSource.pacman]
    aur_pkgs    = [p.name for p in proj.packages if p.source == InstallSource.aur]
    pip_pkgs    = [f"{p.name}=={p.version}" for p in proj.packages if p.source == InstallSource.pip]
    npm_pkgs    = [p.name for p in proj.packages if p.source == InstallSource.npm]
    cargo_pkgs  = [p.name for p in proj.packages if p.source == InstallSource.cargo]
    flatpak_pkgs= [p.name for p in proj.packages if p.source == InstallSource.flatpak]

    lines = [
        "#!/usr/bin/env bash",
        f"# PAPIS reinstall script for project: {proj.name}",
        f"# Generated by PAPIS",
        "",
    ]
    if pacman_pkgs:
        lines += ["# pacman packages", f"sudo pacman -S --needed {' '.join(pacman_pkgs)}", ""]
    if aur_pkgs:
        lines += ["# AUR packages (requires yay or paru)", f"yay -S --needed {' '.join(aur_pkgs)}", ""]
    if pip_pkgs:
        lines += ["# pip packages", f"pip install {' '.join(pip_pkgs)}", ""]
    if npm_pkgs:
        lines += ["# npm global packages", f"npm install -g {' '.join(npm_pkgs)}", ""]
    if cargo_pkgs:
        lines += ["# cargo packages", f"cargo install {' '.join(cargo_pkgs)}", ""]
    if flatpak_pkgs:
        lines += ["# flatpak packages"] + [f"flatpak install {p}" for p in flatpak_pkgs] + [""]

    return "\n".join(lines)


@router.get("/{proj_id}/snapshot")
def export_snapshot(proj_id: int, db: Session = Depends(get_db)):
    """Full JSON snapshot of a project and all its packages."""
    proj = db.query(Project).get(proj_id)
    if not proj:
        raise HTTPException(404)
    return {
        "project": {
            "id": proj.id,
            "name": proj.name,
            "description": proj.description,
            "directory": proj.directory,
            "tags": json.loads(proj.tags or "[]"),
        },
        "packages": [
            {
                "name": p.name,
                "version": p.version,
                "source": p.source,
                "install_type": p.install_type,
                "size_bytes": p.size_bytes,
                "description": p.description,
            }
            for p in proj.packages
        ],
        "exported_at": utcnow().isoformat(),
    }


@router.get("/{proj_id}/dockerfile", response_class=PlainTextResponse)
def export_dockerfile(proj_id: int, db: Session = Depends(get_db)):
    proj = db.query(Project).get(proj_id)
    if not proj:
        raise HTTPException(404)

    pip_pkgs = [f"{p.name}=={p.version}" for p in proj.packages if p.source == InstallSource.pip]
    npm_pkgs = [p.name for p in proj.packages if p.source == InstallSource.npm]

    lines = [
        "FROM archlinux:latest",
        "",
        "RUN pacman -Syu --noconfirm \\",
    ]
    pacman_pkgs = [p.name for p in proj.packages if p.source == InstallSource.pacman]
    if pacman_pkgs:
        lines.append(f"    {' '.join(pacman_pkgs)}")
    lines.append("")

    if pip_pkgs:
        lines += [
            "RUN pip install --no-cache-dir \\",
            "    " + " \\\n    ".join(pip_pkgs),
            "",
        ]
    if npm_pkgs:
        lines += [f"RUN npm install -g {' '.join(npm_pkgs)}", ""]

    lines += [f"WORKDIR /app", "CMD [\"/bin/bash\"]"]
    return "\n".join(lines)